site_name: Programación DAM
site_url: https://jmabadlopez.github.io/programacion/site/

nav:
  - Unidades:
    - UD1 - Introducción a la programación. Lenguaje Java: unidades/ud01.md
    - UD2 - Programación estructurada. Estructuras de control y repetición: unidades/ud02.md
    - UD3 - Funciones y procedimientos: unidades/ud03.md
    - UD4 - Estructuras de datos dinámicas: unidades/ud04.md
    - UD5 - Programación Orientada a Objetos (POO): unidades/ud05.md
    - UD6 - POO Avanzada: unidades/ud06.md
    - UD7 - Ficheros y Excepciones: unidades/ud07.md
    - UD8 - Acceso a Bases de Datos: unidades/ud08.md
    - UD9 - Interfaces gráficas con JavaFX: 
      - Introducción: unidades/ud09/introduccion.md
      - Elementos de una interfaz: unidades/ud09/elementos.md
      - Navegación entre pantallas: unidades/ud09/navegacion.md
      - Menús y layouts: unidades/ud09/menus.md
      - Integración de datos con BBDD: unidades/ud09/integracion_datos.md
      - Reto Final: unidades/ud09/reto_final.md
  - Ejercicios:
    - UD1 - Introducción a la programación. Lenguaje Java:
      - Ejercicios de introducción: ejercicios/ud01/introduccion.md
      - Ejercicios del lenguaje Java: ejercicios/ud01/lenguaje_java.md
    - UD2 - Programación estructurada. Estructuras de control y repetición:
      - Ejercicios de programación estructurada: ejercicios/ud02/ejercicios_ud02.md
      - Ejercicios de condicionales y bucles: ejercicios/ud02/ejercicios_ud02_bucles.md
      - Actividades entregables: ejercicios/ud02/entregable_ud02.md
    - UD3 - Funciones y procedimientos:
      - Ejercicios de funciones y procedimientos: ejercicios/ud03/ejercicios_ud03_inicio.md
      - Actividad entregable. Gestor de Inventario de Ferreteria: ejercicios/ud03/ejercicio_ud03_ferreteria.md
      - Actividad (EXTRA). Analizador de textos: ejercicios/ud03/ejercicio_ud03_analizador_texto.md
    - UD4 - Estructuras de datos dinámicas:
      - Ejercicios de listas: ejercicios/ud04/ejercicios_ud4_arraylist_inicio.md
      - Ejercicios avanzados de listas: ejercicios/ud04/ejercicios_ud4_listas_avanzado.md
      - Ejercicios de conjuntos y mapas: ejercicios/ud04/ejercicios_ud4_set_map.md
      - Actividad entregable. La logística de Santa Claus: ejercicios/ud04/ejercicios_ud4_entregable.md
    - UD5 - Programación Orientada a Objetos (POO):
      - Ejercicios de iniciación de POO: ejercicios/ud05/ejercicios_ud05_inicio.md
      - Ejercicios avanzados de POO: ejercicios/ud05/ejercicios_ud05_avanzado.md
      - Actividad entregable. Gestión de un cine: ejercicios/ud05/ejercicio_ud05_entregable.md
    - UD6 - POO Avanzada:
      - Ejercicios de POO avanzada: ejercicios/ud06/ejercicios_ud6.md
      - Ejercicios de POO. Juego de Rol: ejercicios/ud06/ejercicios_ud6_juego_rol.md
    - UD7 - Ficheros y Excepciones:
      - Ejercicios de Ficheros y Excepciones: ejercicios/ud07/ejercicios_ud07.md
      - Actividad entregable. Gestión de Almacén con Persistencia: ejercicios/ud07/ejercicio_ud07_entregable.md
    - UD8 - Acceso a Bases de Datos:
      - Actividad entregable. Bloc de notas: ejercicios/ud08/ejercicio_ud08_entregable.md
    - UD9 - Interfaces gráficas con JavaFX:
      - Actividad entregable. Gestión de Vuelos: ejercicios/ud09/ejercicio_ud09_entregable.md
  - Recursos:
    - Guías:
      - Instalación IntelliJ: recursos/guia_intellij.md
    - Infografías:
      - Bucles: recursos/bucles.html
      - Array List: recursos/arraylist.html
    - Algorítmica:
      - Básica: recursos/algoritmica_basica.md
      - Método de la burbuja (ordenación): recursos/burbuja.html
      - Recursividad: recursos/recursividad.html
    - Otros:
      - Propuesta de Proyecto: recursos/propuesta_proyecto.md
  - Presentación: index.md

repo_url: https://github.com/jmabadlopez/programacion
repo_name: jmabadlopez/programacion

theme:
  name: material
  language: es
  logo: ./assets/images/camp.png
  favicon: ./assets/images/camp.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  font: 
    code: Roboto Mono
  hljs_languages:
    - python
    - java
    - c
  features:
    - optimize
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Modo oscuro
      primary: red
      accent: red 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo claro
      primary: red
      accent: red
markdown_extensions:
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/jmabadlopez/programacion
# plugins:
#   - to-pdf:
#       author: José Manuel Abad López
#       copyright: 🄯 Creative Commons CC BY-SA 4.0 2025
#       cover_title: Programación
#       cover_subtitle: 1º DAM
#       toc_title: "Contenidos"
#       toc_level: 3
#       output_path: ../public/libro.pdf